-- CreateEnum
CREATE TYPE "memory_status" AS ENUM ('pending', 'approved', 'rejected');

-- CreateTable
CREATE TABLE "memories" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "handle" VARCHAR(30) NOT NULL,
    "public_id" TEXT NOT NULL,
    "caption" VARCHAR(140) NOT NULL,
    "happened_on" DATE NOT NULL,
    "width" INTEGER NOT NULL,
    "height" INTEGER NOT NULL,
    "status" "memory_status" NOT NULL DEFAULT 'pending'::memory_status,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

    CONSTRAINT "memories_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "memories_public_id_key" ON "memories"("public_id");

-- CreateIndex
CREATE INDEX "memories_status_happened_on_idx" ON "memories"("status", "happened_on");

-- CreateIndex
CREATE INDEX "memories_handle_created_at_idx" ON "memories"("handle", "created_at");

-- ============================================================================
-- Everything below is hand-written (not generated by Prisma): the runtime role,
-- its grants and row-level security.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Runtime role
--
-- Neon's owner role (neondb_owner, a member of neon_superuser) has BYPASSRLS, so
-- the app must never run as the owner: it connects as app_user, which is
-- NOBYPASSRLS. The owner is only for migrations (DIRECT_URL).
--
-- The role is created NOLOGIN on purpose. No password lives in this repository:
-- the setup step runs, out of band and once,
--   ALTER ROLE app_user LOGIN PASSWORD '<generated secret>';
-- Idempotent, so re-running the migration against a database that already has
-- the role is safe.
-- ----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user NOLOGIN NOBYPASSRLS;
  END IF;
END
$$;

-- ----------------------------------------------------------------------------
-- Grants
--
-- app_user can read memories and insert only the columns a visitor controls.
-- id, status and created_at therefore always come from the column defaults
-- (the Prisma schema uses DB-side defaults so the client never sends them).
-- No UPDATE or DELETE grant: the runtime role cannot change or remove rows.
-- ----------------------------------------------------------------------------
GRANT USAGE ON SCHEMA public TO app_user;
GRANT SELECT ON "memories" TO app_user;
GRANT INSERT ("handle", "public_id", "caption", "happened_on", "width", "height")
  ON "memories" TO app_user;

-- ----------------------------------------------------------------------------
-- Row-level security on memories
--
-- FORCE makes the policies apply to the table owner as well, except for roles
-- with BYPASSRLS (which is why the runtime must not be the owner).
-- ----------------------------------------------------------------------------
ALTER TABLE "memories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "memories" FORCE ROW LEVEL SECURITY;

-- The visitor handle is passed per transaction by the application:
--   SELECT set_config('app.handle', '<handle>', true);
-- Outside such a transaction the setting is NULL, or '' after one has ended on
-- the same pooled connection. NULLIF turns '' into NULL, so an unset handle
-- matches no row (NULL = anything is not true).

-- Anyone can read approved memories; a visitor also sees their own rows in any
-- status. Own rows must stay visible to INSERT ... RETURNING: PostgreSQL
-- requires rows returned by a modifying query to satisfy the SELECT policy,
-- and raises an error otherwise (CREATE POLICY docs, "SELECT" section).
CREATE POLICY memories_select ON "memories"
  FOR SELECT TO app_user
  USING (
    status = 'approved'
    OR handle = NULLIF(current_setting('app.handle', true), '')
  );

-- A visitor can only insert pending rows under their own handle.
CREATE POLICY memories_insert ON "memories"
  FOR INSERT TO app_user
  WITH CHECK (
    status = 'pending'
    AND handle = NULLIF(current_setting('app.handle', true), '')
  );

-- Deliberately no UPDATE or DELETE policies (and no grants): with RLS enabled
-- that is default-deny for app_user. Approval is a manual step run by the owner
-- (which has BYPASSRLS), for example:
--   UPDATE memories SET status = 'approved' WHERE id = '<uuid>';

-- ----------------------------------------------------------------------------
-- Prisma's bookkeeping table
--
-- Prisma creates _prisma_migrations before applying any migration, so it exists
-- here. Enable RLS (without FORCE and without policies) and revoke all access
-- from everyone but the owner: app_user and PUBLIC get default-deny, while the
-- owner keeps working and keeps recording migrations. FORCE is skipped on
-- purpose so the migration runner is never locked out of its own table.
-- ----------------------------------------------------------------------------
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "_prisma_migrations" FROM PUBLIC;
REVOKE ALL ON TABLE "_prisma_migrations" FROM app_user;
