-- The local wall-clock time a memory happened, next to its date: filled in by the browser from the photo's EXIF, the
-- start of a recording or an audio file's date, or typed by the visitor. Optional, and with no time zone on purpose:
-- it is the time on the clock where the memory happened, and reads the same for everyone.
-- Written in the shape `prisma migrate diff` (schema to schema) generates, then hand-edited below.
--
-- Expand-only: one new nullable column. Nothing is renamed or dropped, so the code live before the deploy keeps
-- working against the migrated database (it never writes or reads the column).

-- AlterTable
ALTER TABLE "memories" ADD COLUMN     "happened_time" TIME(0);


-- ============================================================================
-- Everything below is hand-written (not generated by Prisma): the grant for the
-- new column. Row-level security is untouched: memories keeps ENABLE + FORCE
-- and its policies (a new column changes nothing about which rows a visitor
-- may read or insert).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Grants
--
-- app_user may insert the new column. SELECT on the table already covers
-- reading it back. Still no UPDATE or DELETE grant, and nothing for PUBLIC.
-- ----------------------------------------------------------------------------
GRANT INSERT (
  "happened_time"
) ON "memories" TO app_user;
