-- Exact location for memories. The visitor said the photo's exact location is what they want, so the position is
-- no longer rounded to 2 decimals: the columns widen to numeric(9,6) (6 decimals, about 10 cm) and lose "approx"
-- from their names. Still opt-in: the server only stores a position when the visitor consented.
--
-- `prisma migrate diff` sees a rename as DROP COLUMN + ADD COLUMN, which would lose the rows and the column
-- privileges, so this migration is written by hand: it widens the type, then renames in place.

-- AlterTable
ALTER TABLE "memories" ALTER COLUMN "approx_latitude" SET DATA TYPE DECIMAL(9,6),
ALTER COLUMN "approx_longitude" SET DATA TYPE DECIMAL(9,6);

-- RenameColumn
ALTER TABLE "memories" RENAME COLUMN "approx_latitude" TO "latitude";
ALTER TABLE "memories" RENAME COLUMN "approx_longitude" TO "longitude";


-- ============================================================================
-- Everything below is hand-written (not generated by Prisma): constraint names
-- and grants. Row-level security is untouched: memories keeps ENABLE + FORCE and
-- its two policies from the init migration.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Guard rails
--
-- The range and pairing checks follow the renamed columns (a CHECK is bound to
-- the column, not to its name), so the database still refuses values outside the
-- globe and a half-set position. Only their names change, to match the columns.
-- The place checks from the previous migration need no change.
-- ----------------------------------------------------------------------------
ALTER TABLE "memories" RENAME CONSTRAINT "memories_approx_latitude_range" TO "memories_latitude_range";
ALTER TABLE "memories" RENAME CONSTRAINT "memories_approx_longitude_range" TO "memories_longitude_range";
ALTER TABLE "memories" RENAME CONSTRAINT "memories_approx_location_paired" TO "memories_location_paired";

-- ----------------------------------------------------------------------------
-- Grants
--
-- Column privileges follow a rename and a type change, so app_user keeps INSERT
-- on the two columns. It is restated here (a no-op when already granted) so the
-- migration says out loud what the runtime role may write. Still no UPDATE or
-- DELETE grant, and nothing for PUBLIC.
-- ----------------------------------------------------------------------------
GRANT INSERT (
  "latitude",
  "longitude"
) ON "memories" TO app_user;
