-- Voice memories: a memory is now a photo, an audio or both. The audio is a Cloudinary `video`-type resource
-- (that is how it stores audio), uploaded as `authenticated` like the photos. Written by hand to be expand-only.
--
-- Production keeps running the previous code until the deploy, so nothing is renamed or dropped: only new nullable
-- columns, and NOT NULL relaxed where a photo can now be absent. The previous code only ever inserts rows with a
-- photo, which every check below accepts.

-- AlterTable
ALTER TABLE "memories" ADD COLUMN     "audio_bytes" INTEGER,
ADD COLUMN     "audio_duration_ms" INTEGER,
ADD COLUMN     "audio_format" TEXT,
ADD COLUMN     "audio_public_id" TEXT,
ALTER COLUMN "public_id" DROP NOT NULL,
ALTER COLUMN "width" DROP NOT NULL,
ALTER COLUMN "height" DROP NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "memories_audio_public_id_key" ON "memories"("audio_public_id");


-- ============================================================================
-- Everything below is hand-written (not generated by Prisma): constraints and
-- grants for the new columns. Row-level security is untouched: memories keeps
-- ENABLE + FORCE and its two policies from the init migration.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Guard rails
--
-- The server decides all of this from what Cloudinary reports; the database refuses anything else, so a bug cannot
-- store a memory with nothing in it, a photo without its size, or half an audio.
--  - a memory has a photo or an audio (or both);
--  - the photo's size is set exactly when the photo is;
--  - the four audio columns are set together or all null;
--  - an audio lasts at most 2 minutes (the server allows a second of recorder drift; this is a looser backstop)
--    and weighs at most 15 MB.
-- ----------------------------------------------------------------------------
ALTER TABLE "memories"
  ADD CONSTRAINT "memories_has_media" CHECK ("public_id" IS NOT NULL OR "audio_public_id" IS NOT NULL),
  ADD CONSTRAINT "memories_photo_paired" CHECK (
    ("public_id" IS NULL) = ("width" IS NULL) AND ("public_id" IS NULL) = ("height" IS NULL)
  ),
  ADD CONSTRAINT "memories_audio_paired" CHECK (
    ("audio_public_id" IS NULL) = ("audio_format" IS NULL)
    AND ("audio_public_id" IS NULL) = ("audio_bytes" IS NULL)
    AND ("audio_public_id" IS NULL) = ("audio_duration_ms" IS NULL)
  ),
  ADD CONSTRAINT "memories_audio_duration_range" CHECK ("audio_duration_ms" IS NULL OR "audio_duration_ms" BETWEEN 1 AND 125000),
  ADD CONSTRAINT "memories_audio_bytes_range" CHECK ("audio_bytes" IS NULL OR "audio_bytes" BETWEEN 1 AND 15728640);

-- ----------------------------------------------------------------------------
-- Grants
--
-- app_user may insert the four columns the server computes from the verified audio. public_id, width and height keep
-- the INSERT grant they already have. SELECT on the table already covers reading them back. Still no UPDATE or DELETE
-- grant, and nothing for PUBLIC.
-- ----------------------------------------------------------------------------
GRANT INSERT (
  "audio_public_id",
  "audio_format",
  "audio_bytes",
  "audio_duration_ms"
) ON "memories" TO app_user;
