-- The color of a memory's orb: `#rrggbb`, picked by the visitor from the swatches of their own photo, or derived by
-- the server from the photo's dominant color. Generated offline with `prisma migrate diff`, then hand-edited below.

-- AlterTable
ALTER TABLE "memories" ADD COLUMN     "orb_color" VARCHAR(7);


-- ============================================================================
-- Everything below is hand-written (not generated by Prisma): a constraint and a
-- grant for the new column. Row-level security is untouched: memories keeps
-- ENABLE + FORCE and its two policies from the init migration.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Guard rails
--
-- The column is nullable because rows stored before this migration have no
-- color; the server derives one for them when it lists. The server only ever
-- stores a valid, glowing color, and the database refuses anything that is not
-- a lowercase #rrggbb, so a bug cannot store text that ends up in a style.
-- ----------------------------------------------------------------------------
ALTER TABLE "memories"
  ADD CONSTRAINT "memories_orb_color_hex" CHECK ("orb_color" IS NULL OR "orb_color" ~ '^#[0-9a-f]{6}$');

-- ----------------------------------------------------------------------------
-- Grants
--
-- app_user may insert the one column the server computes. SELECT on the table
-- already covers reading it back. Still no UPDATE or DELETE grant, and nothing
-- for PUBLIC.
-- ----------------------------------------------------------------------------
GRANT INSERT (
  "orb_color"
) ON "memories" TO app_user;
