-- Place of a memory: a short human label and where it came from (the photo's own GPS, or a Google Maps link the
-- visitor pasted). Generated offline with `prisma migrate diff`, then hand-edited below.

-- CreateEnum
CREATE TYPE "location_source" AS ENUM ('photo', 'link');

-- AlterTable
ALTER TABLE "memories" ADD COLUMN     "location_source" "location_source",
ADD COLUMN     "place_name" VARCHAR(120);


-- ============================================================================
-- Everything below is hand-written (not generated by Prisma): a backfill,
-- constraints and grants for the new columns. Row-level security is untouched:
-- memories keeps ENABLE + FORCE and its two policies from the init migration.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Backfill
--
-- Rows stored by the previous migration have an approximate location that can
-- only have come from the photo's own GPS. Mark them so the constraint below
-- holds. (Runs as the migration owner; a no-op when no row has a location.)
-- ----------------------------------------------------------------------------
UPDATE "memories" SET "location_source" = 'photo' WHERE "approx_latitude" IS NOT NULL;

-- ----------------------------------------------------------------------------
-- Guard rails
--
-- The source is set if and only if the approximate location is, and a place
-- name only ever describes a stored location. The server decides all of this;
-- the database refuses anything else, so a bug cannot store a name for nothing.
-- ----------------------------------------------------------------------------
ALTER TABLE "memories"
  ADD CONSTRAINT "memories_location_source_paired" CHECK (("location_source" IS NULL) = ("approx_latitude" IS NULL)),
  ADD CONSTRAINT "memories_place_name_needs_location" CHECK ("place_name" IS NULL OR "approx_latitude" IS NOT NULL);

-- ----------------------------------------------------------------------------
-- Grants
--
-- app_user may insert the two columns the server computes. SELECT on the table
-- already covers reading them back. Still no UPDATE or DELETE grant, and
-- nothing for PUBLIC.
-- ----------------------------------------------------------------------------
GRANT INSERT (
  "place_name",
  "location_source"
) ON "memories" TO app_user;
