-- Photo details for memories: media kind, format, size, taken date, colors, whitelisted EXIF metadata and an
-- opt-in approximate (about 1 km) location. Generated offline with `prisma migrate diff`, then hand-edited below.

-- CreateEnum
CREATE TYPE "media_kind" AS ENUM ('image');

-- AlterTable
ALTER TABLE "memories" ADD COLUMN     "approx_latitude" DECIMAL(5,2),
ADD COLUMN     "approx_longitude" DECIMAL(5,2),
ADD COLUMN     "bytes" INTEGER,
ADD COLUMN     "dominant_color" VARCHAR(7),
ADD COLUMN     "format" TEXT,
ADD COLUMN     "kind" "media_kind" NOT NULL DEFAULT 'image',
ADD COLUMN     "metadata" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "palette" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "taken_at" TIMESTAMPTZ(3);


-- ============================================================================
-- Everything below is hand-written (not generated by Prisma): constraints and
-- grants for the new columns. Row-level security is untouched: memories keeps
-- ENABLE + FORCE and its two policies from the init migration.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Guard rails
--
-- The approximate location is rounded to 2 decimals by the server (about 1 km)
-- and only stored with the visitor's consent. The database still refuses
-- values outside the globe and a half-set position, so a bug cannot store one.
-- ----------------------------------------------------------------------------
ALTER TABLE "memories"
  ADD CONSTRAINT "memories_approx_latitude_range" CHECK ("approx_latitude" BETWEEN -90 AND 90),
  ADD CONSTRAINT "memories_approx_longitude_range" CHECK ("approx_longitude" BETWEEN -180 AND 180),
  ADD CONSTRAINT "memories_approx_location_paired" CHECK (("approx_latitude" IS NULL) = ("approx_longitude" IS NULL)),
  ADD CONSTRAINT "memories_dominant_color_hex" CHECK ("dominant_color" IS NULL OR "dominant_color" ~ '^#[0-9a-f]{6}$');

-- ----------------------------------------------------------------------------
-- Grants
--
-- app_user may insert the columns a visitor or the server computes from the
-- verified photo: kind, format, bytes, taken_at, dominant_color, palette,
-- metadata and the approximate location. SELECT on the table already covers
-- reading them back. Still no UPDATE or DELETE grant, and nothing for PUBLIC.
-- ----------------------------------------------------------------------------
GRANT INSERT (
  "kind",
  "format",
  "bytes",
  "taken_at",
  "dominant_color",
  "palette",
  "metadata",
  "approx_latitude",
  "approx_longitude"
) ON "memories" TO app_user;
