-- Memory views: one row per (memory, visitor) saying that this Instagram account opened this approved memory, and a
-- counter of DISTINCT viewers on the memory itself. Generated offline with `prisma migrate diff`, then hand-edited.
--
-- Expand-only: one new column with a default, and a new table. Production keeps running the previous code
-- until the deploy; that code never reads or writes any of this.

-- AlterTable
ALTER TABLE "memories" ADD COLUMN     "view_count" INTEGER NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "memory_views" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "memory_id" UUID NOT NULL,
    "handle" VARCHAR(30) NOT NULL,
    "first_viewed_at" TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    "last_viewed_at" TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    "open_count" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "memory_views_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "memory_views_memory_id_idx" ON "memory_views"("memory_id");

-- CreateIndex
CREATE UNIQUE INDEX "memory_views_memory_id_handle_key" ON "memory_views"("memory_id", "handle");

-- AddForeignKey
ALTER TABLE "memory_views" ADD CONSTRAINT "memory_views_memory_id_fkey" FOREIGN KEY ("memory_id") REFERENCES "memories"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ============================================================================
-- Everything below is hand-written (not generated by Prisma): constraints,
-- grants, row-level security and the counter trigger.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Guard rails
--  - a row exists because of at least one open, and a counter never goes below zero.
-- ----------------------------------------------------------------------------
ALTER TABLE "memory_views"
  ADD CONSTRAINT "memory_views_open_count_positive" CHECK ("open_count" > 0);

ALTER TABLE "memories"
  ADD CONSTRAINT "memories_view_count_non_negative" CHECK ("view_count" >= 0);

-- ----------------------------------------------------------------------------
-- Grants
--
-- Column-level, for app_user only; nothing for PUBLIC and no DELETE (a view is never taken back).
--  - INSERT (memory_id, handle): the first open. id and the timestamps and the count come from the column defaults.
--  - UPDATE (last_viewed_at, open_count): a later open. The pair (memory_id, handle) never changes.
--  - SELECT: needed by INSERT ... ON CONFLICT DO UPDATE (the conflict target and the `open_count + 1` are read) and by
--    RETURNING. The row-level policy below limits it to the visitor's own rows.
--
-- memories.view_count gets no grant: app_user can only read it through the table-level SELECT it already has. It is
-- written by the trigger below, never by the application.
-- ----------------------------------------------------------------------------
GRANT INSERT ("memory_id", "handle") ON "memory_views" TO app_user;
GRANT UPDATE ("last_viewed_at", "open_count") ON "memory_views" TO app_user;
GRANT SELECT ("memory_id", "handle", "open_count", "first_viewed_at", "last_viewed_at") ON "memory_views" TO app_user;

-- ----------------------------------------------------------------------------
-- Row-level security on memory_views
--
-- Same shape as memories: ENABLE and FORCE, handle passed per transaction (see with-visitor.ts), NULLIF so an unset
-- handle matches nothing. There is deliberately no DELETE policy.
-- ----------------------------------------------------------------------------
ALTER TABLE "memory_views" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "memory_views" FORCE ROW LEVEL SECURITY;

-- A visitor reads only their own rows: nobody can see who else opened a memory.
CREATE POLICY memory_views_select ON "memory_views"
  FOR SELECT TO app_user
  USING (handle = NULLIF(current_setting('app.handle', true), ''));

-- A visitor inserts only under their own handle, and only for an approved memory somebody else wrote. The server checks
-- the same before it calls; this is the second line of defense. The subquery runs as app_user, so the memories policy
-- applies to it too (an approved memory is visible to everybody).
CREATE POLICY memory_views_insert ON "memory_views"
  FOR INSERT TO app_user
  WITH CHECK (
    handle = NULLIF(current_setting('app.handle', true), '')
    AND EXISTS (
      SELECT 1 FROM "memories" m
      WHERE m.id = memory_id
        AND m.status = 'approved'
        AND m.handle <> NULLIF(current_setting('app.handle', true), '')
    )
  );

-- A visitor updates only their own rows, and the row stays theirs.
CREATE POLICY memory_views_update ON "memory_views"
  FOR UPDATE TO app_user
  USING (handle = NULLIF(current_setting('app.handle', true), ''))
  WITH CHECK (handle = NULLIF(current_setting('app.handle', true), ''));

-- ----------------------------------------------------------------------------
-- The counter
--
-- memories.view_count is the number of rows in memory_views for that memory (distinct visitors). app_user has no UPDATE
-- on memories, so a trigger function does it with its owner's rights:
--  - SECURITY DEFINER: runs as the role that owns the function, which is the migration role that owns the tables. That
--    role has BYPASSRLS on Neon (see the init migration), so the FORCEd policies of memories do not hide the row from it.
--  - SET search_path = public, pg_temp: a definer function must not resolve names through the caller's search_path.
--  - EXECUTE is revoked from PUBLIC: a trigger function is never called directly (PostgreSQL also refuses to call it
--    outside a trigger), and nobody else needs the privilege.
--
-- It is AFTER INSERT ... FOR EACH ROW and nothing else. INSERT ... ON CONFLICT (memory_id, handle) DO UPDATE takes the
-- UPDATE path for a visitor already counted, which fires UPDATE triggers and never the row-level INSERT ones, so a
-- repeat open bumps open_count and last_viewed_at on that row and leaves view_count alone. See odd/tasks/memory-views.md.
-- ----------------------------------------------------------------------------
CREATE FUNCTION "memory_views_count_view"() RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  UPDATE "memories" SET "view_count" = "view_count" + 1 WHERE "id" = NEW."memory_id";
  RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION "memory_views_count_view"() FROM PUBLIC;

CREATE TRIGGER "memory_views_count_view"
  AFTER INSERT ON "memory_views"
  FOR EACH ROW EXECUTE FUNCTION "memory_views_count_view"();
