-- Two additions to a memory, both nullable, so the code live before the deploy keeps working against the migrated
-- database (it never writes or reads either):
--  - related_memory_id: the memory this one was contributed from. An explicit relation, drawn as a strong link in the
--    constellation. A self-reference with ON DELETE SET NULL, so removing a memory never removes the ones around it.
--  - place_address: the street address of the stored location ("Av. Rivadavia 1234, Junín").
-- Generated offline with `prisma migrate diff` (schema to schema), then hand-edited below.
--
-- Expand-only: two new nullable columns, an index and a foreign key. Nothing is renamed or dropped.

-- AlterTable
ALTER TABLE "memories" ADD COLUMN     "place_address" VARCHAR(200),
ADD COLUMN     "related_memory_id" UUID;

-- CreateIndex
CREATE INDEX "memories_related_memory_id_idx" ON "memories"("related_memory_id");

-- AddForeignKey
ALTER TABLE "memories" ADD CONSTRAINT "memories_related_memory_id_fkey" FOREIGN KEY ("related_memory_id") REFERENCES "memories"("id") ON DELETE SET NULL ON UPDATE CASCADE;


-- ============================================================================
-- Everything below is hand-written (not generated by Prisma): a constraint,
-- grants and the insert policy. Row-level security is untouched in kind:
-- memories keeps ENABLE + FORCE and its policies from the init migration.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Guard rails
--
-- An address only ever describes a stored location, like the place name does (see memory_place). The server decides
-- all of this; the database refuses anything else, so a bug cannot store an address for nothing.
-- ----------------------------------------------------------------------------
ALTER TABLE "memories"
  ADD CONSTRAINT "memories_place_address_needs_location" CHECK ("place_address" IS NULL OR "latitude" IS NOT NULL);

-- ----------------------------------------------------------------------------
-- Grants
--
-- app_user may insert the two new columns. SELECT on the table already covers reading them back. Still no UPDATE or
-- DELETE grant (a relation is set once, when the memory is created), and nothing for PUBLIC.
-- ----------------------------------------------------------------------------
GRANT INSERT (
  "related_memory_id",
  "place_address"
) ON "memories" TO app_user;

-- ----------------------------------------------------------------------------
-- Integrity of the relation under row-level security
--
-- A foreign key is checked by the system and ignores row-level security, so on its own it would let a visitor point at
-- ANY memory id, including a pending one that only its author may see (and learn from the error that it exists). The
-- insert policy therefore also requires the related memory to be an approved one.
--
-- ALTER POLICY, not DROP and CREATE: the policy is replaced in one step, so the table is never left without its insert
-- policy (no policy means default-deny, which would break the code that is live). What the old code inserts stays
-- allowed: it never sets related_memory_id, so the new branch is `IS NULL` for every row it writes.
--
-- The subquery runs as app_user, so the select policy applies to it as well; `status = 'approved'` is restated so it
-- never depends on that. The new row's column is written `"memories"."related_memory_id"` on purpose: a bare name inside
-- the subquery would bind to the subquery's own table.
--
-- Does a policy that subqueries its own table recurse? Only when the policy that gets expanded for the inner reference
-- itself contains a subquery ("infinite recursion detected in policy for relation"). The inner reference is a SELECT, so
-- it expands memories_select, which has none: this insert plans and runs. Verified against a real PostgreSQL (PGlite) by
-- src/shared/db/migrations.pglite.test.ts, which also proves its harness detects a genuinely recursive policy. If
-- memories_select ever gains a subquery, that test fails and this check must move into a SECURITY DEFINER function.
-- ----------------------------------------------------------------------------
ALTER POLICY memories_insert ON "memories"
  WITH CHECK (
    status = 'pending'
    AND handle = NULLIF(current_setting('app.handle', true), '')
    AND (
      "memories"."related_memory_id" IS NULL
      OR EXISTS (
        SELECT 1 FROM "memories" AS related
        WHERE related.id = "memories"."related_memory_id"
          AND related.status = 'approved'
      )
    )
  );
